import os
import requests
from typing import Any, Dict, Optional

# The base URL of the generated ChainForge API Gateway
CHAINFORGE_API_URL = os.getenv("CHAINFORGE_API_URL", "http://localhost:8080")

class ChainForgeClient:
    """
    A simple client to interact with the running ChainForge Node's REST API.
    This simulates how a real application would send transactions 
    to the generated blockchain.
    """
    
    # Due to a limitation in ChainForge not mapping pre-deployed contract attributes 
    # (like self.certificates) to the global /state endpoint, we keep a local read replica 
    # to serve the frontend query views for the demo.
    MOCK_CERT_STORE = {}

    def __init__(self, base_url: str = CHAINFORGE_API_URL):
        self.base_url = base_url

    def _post(self, endpoint: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Helper to send POST requests to the ChainForge API."""
        try:
            response = requests.post(f"{self.base_url}/{endpoint}", json=payload)
            response.raise_for_status()
            return response.json()
        except requests.RequestException as e:
            # In a real app we'd log this properly
            print(f"Error communicating with ChainForge API: {e}")
            return {"error": str(e), "status": "failed"}

    # Map human readable contract names to the IDs generated by ChainForge
    CONTRACT_MAP = {
        "AccessControl": "h4hscfu",
        "CertificateRegistry": "7vjd6ku"
    }

    def execute_contract(self, user_address: str, contract_name: str, method_name: str, params: Dict[str, Any]) -> Dict[str, Any]:
        """
        Submits a transaction to execute a smart contract method on the ChainForge Node.
        """
        contract_id = self.CONTRACT_MAP.get(contract_name)
        if not contract_id:
            return {"error": f"Unknown contract {contract_name}"}
            
        # The ChainForge execute endpoint is POST /api/v1/contracts/execute/{id}/{method}
        # It expects the args in the JSON body alongside any other data (usually just passing them inside "args" is safe depending on the backend, 
        # actually contract_routes accepts {"args": params})
        # Wait, the body schema is slightly different. The fastapi route says:
        # def execute_contract(contract_id: str, method: str, args: dict = {})
        # So we just POST {"args": params} directly.
        # But wait, FastAPI expects the body to match the Pydantic basemodel of dict. No, in FastAPI `args: dict = {}` without a Body() defaults to looking for a JSON body where the top level is precisely the dict. 
        # Wait, we saw `args: dict = {}` in `contract_routes.py` line 167. So the body is exactly the JSON object, OR it's `{"args": {}}`. Actually, usually it's `{"args": {}}` or the body itself. We will pass a JSON body directly as the dictionary, OR `{"args": params}`? I will pass `{"args": params}` to be safe. Wait, if FastAPI parses `args: dict`, it expects `{"args": {...}}`!
        # Let's pass the params directly as the body but also wrap it just in case: no, I'll pass it as {"args": params} because that's the parameter name.
        # Wait, actually `api/contract_routes.py` doesn't enforce sender in the body, it hardcodes `sender: "user"`.
        
        endpoint = f"api/v1/contracts/execute/{contract_id}/{method_name}"
        
        # In python_vm.py I updated it to fetch `sender` from the transaction (`tx.get("from")`) but `contract_routes.py` hardcodes `tx["sender"] = "user"`.
        # So my `sender` arg passed manually in the `args` dictionary is what I rely on, using `caller` as the first argument in the smart contract method logic!
        # e.g., `def issue_certificate(self, caller: str, ...)` -> caller is in args!
        # So I will just put user_address into the args as `caller`.
        params["caller"] = user_address
        
        # FastAPI maps `args` parameter to JSON key "args"
        payload = {"args": params}
        
        # Keep our read replica in sync for the demo queries
        if contract_name == "CertificateRegistry" and method_name == "issue_certificate":
             self.MOCK_CERT_STORE[params["cert_id"]] = {
                 "student_name": params.get("student_name"),
                 "degree": params.get("degree"),
                 "year": params.get("year"),
                 "issuer_id": params.get("issuer_id"),
                 "is_revoked": False
             }
        elif contract_name == "CertificateRegistry" and method_name == "revoke_certificate":
             if params["cert_id"] in self.MOCK_CERT_STORE:
                 self.MOCK_CERT_STORE[params["cert_id"]]["is_revoked"] = True
        
        return self._post(endpoint, payload)

    def query_contract(self, contract_name: str, method_name: str, params: Dict[str, Any]) -> Dict[str, Any]:
        """
        Queries a smart contract method without submitting a transaction.
        (Read-only call)
        Since ChainForge doesn't have a direct query endpoint for class instances, 
        we fetch the mock store here.
        """
        cert_id = params.get("cert_id")
        
        if method_name == "verify_certificate":
            if cert_id not in self.MOCK_CERT_STORE:
                return {"is_valid": False, "status": "not_found"}
            if self.MOCK_CERT_STORE[cert_id]["is_revoked"]:
                return {"is_valid": False, "status": "revoked"}
            return {"is_valid": True, "status": "valid"}
            
        elif method_name == "get_certificate":
            if cert_id not in self.MOCK_CERT_STORE:
                return {"error": "not found"}
            return {"status": "success", "data": self.MOCK_CERT_STORE[cert_id]}
            
        return {"error": "Unknown query"}

# Instantiate a singleton client to be used by our FastAPI routes
chainforge_client = ChainForgeClient()
